package com.pulsoetico.pulsoetico.models;

public enum Permissoes {
    VISUALIZAR_DASHBOARD,
    GERENCIAR_EMPRESA,
    GERENCIAR_CARGOS,
    GERENCIAR_MEMBROS,
    GERENCIAR_SETORES,
    GERENCIAR_PESQUISAS,
    RESPONDER_PESQUISAS,
    GERENCIAR_DENUNCIAS,
    RESPONDER_DENUNCIAS,
    GERENCIAR_JORNADAS,
    REGISTRAR_PONTO
}